export type SearchCategory =
  | "Pages"
  | "Departments"
  | "Flow Stages"
  | "Staff & Rooms"
  | "Metrics"
  | "Charts & Views"
  | "Recommendations"
  | "Simulation";

export interface SearchItem {
  id: string;
  title: string;
  subtitle?: string;
  url: string;
  keywords: string[];
  aliases?: string[];
  category: SearchCategory;
}

export const SEARCH_INDEX: SearchItem[] = [
  // ── Pages ──────────────────────────────────────────────────────────────────
  {
    id: "page-dashboard",
    title: "Dashboard",
    subtitle: "Operations overview, KPIs, and live clinic signals",
    url: "/",
    keywords: ["home", "overview", "operations", "dashboard", "kpi", "live"],
    aliases: ["main", "ops"],
    category: "Pages",
  },
  {
    id: "page-analytics",
    title: "Analytics & Outcomes",
    subtitle: "Before vs. after AI optimization performance",
    url: "/analytics",
    keywords: ["analytics", "outcomes", "reports", "performance", "stats", "comparison"],
    aliases: ["reporting", "results"],
    category: "Pages",
  },
  {
    id: "page-patient-flow",
    title: "Patient Flow",
    subtitle: "Pipeline stages, rooms, queues, and heatmaps",
    url: "/patient-flow",
    keywords: ["flow", "pipeline", "patients", "movement", "visualization"],
    aliases: ["patient pipeline", "flow map"],
    category: "Pages",
  },
  {
    id: "page-recommendations",
    title: "AI Recommendations",
    subtitle: "Ranked operational suggestions with impact scores",
    url: "/recommendations",
    keywords: ["ai", "recommendations", "suggestions", "advice", "optimize", "engine"],
    aliases: ["recs", "suggestions"],
    category: "Pages",
  },
  {
    id: "page-simulation",
    title: "What-If Simulation",
    subtitle: "Adjust staffing and capacity to re-forecast outcomes",
    url: "/simulation",
    keywords: ["simulation", "what if", "scenario", "forecast", "sliders", "controls"],
    aliases: ["what-if", "sim", "model"],
    category: "Pages",
  },

  // ── Departments ────────────────────────────────────────────────────────────
  {
    id: "dept-pediatrics",
    title: "Pediatrics",
    subtitle: "82% load — high congestion risk, surge expected at 14:30",
    url: "/patient-flow",
    keywords: ["pediatric", "pediatrics", "children", "kids", "peds", "alvarez"],
    aliases: ["peds dept", "child clinic"],
    category: "Departments",
  },
  {
    id: "dept-cardiology",
    title: "Cardiology",
    subtitle: "64% load — moderate utilization, Dr. Chen on schedule",
    url: "/patient-flow",
    keywords: ["cardiology", "heart", "cardiac", "cardio"],
    aliases: ["heart clinic"],
    category: "Departments",
  },
  {
    id: "dept-urgent-care",
    title: "Urgent Care",
    subtitle: "91% load — highest current load, surge between 13:00–15:00",
    url: "/patient-flow",
    keywords: ["urgent", "urgent care", "emergency", "walk-in", "er"],
    aliases: ["emergency room", "walk in"],
    category: "Departments",
  },
  {
    id: "dept-general",
    title: "General",
    subtitle: "47% load — spare room capacity, Room 4 available",
    url: "/patient-flow",
    keywords: ["general", "primary care", "gp", "family medicine"],
    aliases: ["primary", "general practice"],
    category: "Departments",
  },
  {
    id: "dept-radiology",
    title: "Radiology",
    subtitle: "38% load — imaging and referral coordination",
    url: "/patient-flow",
    keywords: ["radiology", "imaging", "x-ray", "scan", "mri", "ct"],
    aliases: ["imaging dept", "xray"],
    category: "Departments",
  },

  // ── Flow Stages ────────────────────────────────────────────────────────────
  {
    id: "stage-arrival",
    title: "Arrival",
    subtitle: "28 patients — first stage in the flow pipeline",
    url: "/patient-flow",
    keywords: ["arrival", "arrivals", "entrance", "front door", "walk in"],
    category: "Flow Stages",
  },
  {
    id: "stage-checkin",
    title: "Check-In",
    subtitle: "14 patients — front desk and kiosk intake",
    url: "/patient-flow",
    keywords: ["check-in", "checkin", "check in", "registration", "intake", "front desk", "kiosk"],
    aliases: ["registration desk"],
    category: "Flow Stages",
  },
  {
    id: "stage-waiting",
    title: "Waiting",
    subtitle: "22 patients — pre-exam queue and lounge dwell",
    url: "/patient-flow",
    keywords: ["waiting", "wait room", "lobby", "queue", "waiting area"],
    category: "Flow Stages",
  },
  {
    id: "stage-triage",
    title: "Triage",
    subtitle: "6 patients — acuity assessment before exam",
    url: "/patient-flow",
    keywords: ["triage", "assessment", "acuity", "nurse triage"],
    category: "Flow Stages",
  },
  {
    id: "stage-in-exam",
    title: "In Exam",
    subtitle: "9 patients — active provider encounters",
    url: "/patient-flow",
    keywords: ["exam", "in exam", "examination", "provider", "doctor visit", "seen"],
    aliases: ["with doctor", "being seen"],
    category: "Flow Stages",
  },
  {
    id: "stage-checkout",
    title: "Checkout",
    subtitle: "4 patients — discharge and follow-up scheduling",
    url: "/patient-flow",
    keywords: ["checkout", "check out", "discharge", "leaving", "departure"],
    category: "Flow Stages",
  },
  {
    id: "stage-intake-bottleneck",
    title: "Intake Bottlenecks",
    subtitle: "Stages exceeding target dwell time",
    url: "/patient-flow",
    keywords: ["bottleneck", "intake", "dwell time", "slow", "backlog", "delay"],
    aliases: ["slow intake", "intake delay"],
    category: "Flow Stages",
  },

  // ── Staff & Rooms ──────────────────────────────────────────────────────────
  {
    id: "staff-alvarez",
    title: "Dr. Alvarez",
    subtitle: "Pediatrics — 92% session load today",
    url: "/patient-flow",
    keywords: ["alvarez", "dr alvarez", "doctor alvarez", "pediatrician"],
    category: "Staff & Rooms",
  },
  {
    id: "staff-chen",
    title: "Dr. Chen",
    subtitle: "Cardiology — 71% session load, afternoon block at 15:00",
    url: "/patient-flow",
    keywords: ["chen", "dr chen", "doctor chen", "cardiologist"],
    category: "Staff & Rooms",
  },
  {
    id: "staff-patel",
    title: "Dr. Patel",
    subtitle: "Urgent Care — 88% session load",
    url: "/patient-flow",
    keywords: ["patel", "dr patel", "doctor patel"],
    category: "Staff & Rooms",
  },
  {
    id: "staff-okafor",
    title: "Dr. Okafor",
    subtitle: "General — 54% session load",
    url: "/patient-flow",
    keywords: ["okafor", "dr okafor", "doctor okafor"],
    category: "Staff & Rooms",
  },
  {
    id: "staff-lindberg",
    title: "Dr. Lindberg",
    subtitle: "Radiology — 36% session load",
    url: "/patient-flow",
    keywords: ["lindberg", "dr lindberg", "doctor lindberg", "radiologist"],
    category: "Staff & Rooms",
  },
  {
    id: "room-4",
    title: "Room 4",
    subtitle: "General exam room — idle 38%, candidate for Urgent Care reassignment",
    url: "/recommendations",
    keywords: ["room 4", "room four", "exam room 4", "reassign room"],
    aliases: ["room four"],
    category: "Staff & Rooms",
  },
  {
    id: "room-map",
    title: "Exam Room Map",
    subtitle: "12 rooms — occupied, cleaning, and available status",
    url: "/patient-flow",
    keywords: ["room map", "exam rooms", "rooms", "occupancy", "available rooms", "occupied"],
    aliases: ["room status", "room availability"],
    category: "Staff & Rooms",
  },
  {
    id: "staff-nurses",
    title: "Nurses on Shift",
    subtitle: "Front-desk and clinical nursing coverage",
    url: "/simulation",
    keywords: ["nurses", "nursing", "rn", "nurse staffing", "nurse shift"],
    aliases: ["nursing staff"],
    category: "Staff & Rooms",
  },
  {
    id: "staff-doctors-shift",
    title: "Doctors on Shift",
    subtitle: "Provider coverage and availability",
    url: "/simulation",
    keywords: ["doctors", "physicians", "providers", "doctor shift", "on shift"],
    aliases: ["physician staffing"],
    category: "Staff & Rooms",
  },

  // ── Metrics ────────────────────────────────────────────────────────────────
  {
    id: "metric-wait-time",
    title: "Wait Time",
    subtitle: "Average minutes patients wait before being seen",
    url: "/",
    keywords: ["wait", "wait time", "delay", "minutes", "queue time", "avg wait"],
    aliases: ["waiting time", "patient delay"],
    category: "Metrics",
  },
  {
    id: "metric-estimated-delay",
    title: "Estimated Delay",
    subtitle: "Projected additional delay beyond scheduled appointment time",
    url: "/",
    keywords: ["estimated delay", "delay", "behind schedule", "running late"],
    category: "Metrics",
  },
  {
    id: "metric-congestion",
    title: "Congestion Risk",
    subtitle: "Clinic-wide capacity pressure and bottleneck probability",
    url: "/",
    keywords: ["congestion", "busy", "overload", "bottleneck", "capacity", "risk score"],
    aliases: ["crowded", "overloaded"],
    category: "Metrics",
  },
  {
    id: "metric-queue",
    title: "Queue Length",
    subtitle: "Patients waiting in intake and exam queues",
    url: "/patient-flow",
    keywords: ["queue", "line", "backlog", "build-up", "queue length"],
    aliases: ["waiting line"],
    category: "Metrics",
  },
  {
    id: "metric-room-util",
    title: "Room Utilization",
    subtitle: "Percentage of exam rooms actively in use",
    url: "/simulation",
    keywords: ["room", "utilization", "exam room", "capacity", "room util"],
    category: "Metrics",
  },
  {
    id: "metric-checked-in",
    title: "Patients Checked In",
    subtitle: "Total patients registered today",
    url: "/",
    keywords: ["checked in", "check in count", "registered", "intake count"],
    category: "Metrics",
  },
  {
    id: "metric-active-appts",
    title: "Active Appointments",
    subtitle: "Currently in-progress scheduled visits",
    url: "/",
    keywords: ["active appointments", "appointments", "in progress", "sessions"],
    aliases: ["ongoing visits"],
    category: "Metrics",
  },
  {
    id: "metric-doctors-available",
    title: "Doctors Available",
    subtitle: "Providers not currently in active encounters",
    url: "/",
    keywords: ["doctors available", "available providers", "free doctors"],
    category: "Metrics",
  },
  {
    id: "metric-throughput",
    title: "Throughput",
    subtitle: "Patients seen per hour — current vs. AI-optimized",
    url: "/analytics",
    keywords: ["throughput", "patients per hour", "volume", "productivity"],
    aliases: ["patients/hr"],
    category: "Metrics",
  },
  {
    id: "metric-staff-efficiency",
    title: "Staff Efficiency",
    subtitle: "Operational profile — +23% with AI optimization",
    url: "/analytics",
    keywords: ["staff efficiency", "efficiency", "productivity", "staff eff"],
    category: "Metrics",
  },
  {
    id: "metric-patient-satisfaction",
    title: "Patient Satisfaction",
    subtitle: "+0.7 NPS weekly survey improvement",
    url: "/analytics",
    keywords: ["patient satisfaction", "nps", "satisfaction", "survey", "experience"],
    aliases: ["net promoter"],
    category: "Metrics",
  },
  {
    id: "metric-dwell-time",
    title: "Dwell Time",
    subtitle: "Time patients spend in each flow stage",
    url: "/patient-flow",
    keywords: ["dwell time", "stage time", "time in stage", "lingering"],
    category: "Metrics",
  },
  {
    id: "metric-scheduling",
    title: "Scheduling",
    subtitle: "Appointments, delays, and session load balancing",
    url: "/recommendations",
    keywords: ["scheduling", "appointments", "calendar", "bookings", "slots"],
    aliases: ["appointment scheduling"],
    category: "Metrics",
  },
  {
    id: "metric-staff-overtime",
    title: "Staff Overtime",
    subtitle: "−28% via smarter AI-driven scheduling",
    url: "/analytics",
    keywords: ["overtime", "staff overtime", "extra hours", "shift overrun"],
    category: "Metrics",
  },

  // ── Charts & Views ─────────────────────────────────────────────────────────
  {
    id: "chart-wait-congestion-live",
    title: "Wait Time & Congestion (Live)",
    subtitle: "Streaming operational signal — last 30 minutes",
    url: "/",
    keywords: ["live chart", "streaming", "wait congestion chart", "area chart"],
    category: "Charts & Views",
  },
  {
    id: "chart-predicted-congestion",
    title: "Predicted Congestion",
    subtitle: "Next 30 minutes clinic-wide risk gauge",
    url: "/",
    keywords: ["predicted", "forecast congestion", "risk gauge", "radial"],
    category: "Charts & Views",
  },
  {
    id: "chart-department-load",
    title: "Department Load",
    subtitle: "Capacity pressure bar by department",
    url: "/",
    keywords: ["department load", "load chart", "capacity pressure"],
    category: "Charts & Views",
  },
  {
    id: "chart-flow-pipeline",
    title: "Flow Pipeline",
    subtitle: "Patient volume across all stages",
    url: "/patient-flow",
    keywords: ["flow pipeline", "pipeline chart", "stage volume"],
    category: "Charts & Views",
  },
  {
    id: "chart-queue-buildup",
    title: "Queue Build-Up",
    subtitle: "Delays compounding through the day",
    url: "/patient-flow",
    keywords: ["queue build-up", "queue buildup", "queue chart", "line chart"],
    category: "Charts & Views",
  },
  {
    id: "chart-congestion-heatmap",
    title: "Congestion Heatmap",
    subtitle: "Department × hour intensity grid",
    url: "/patient-flow",
    keywords: ["heatmap", "heat map", "congestion heatmap", "hourly intensity"],
    aliases: ["heat map"],
    category: "Charts & Views",
  },
  {
    id: "chart-doctor-schedule",
    title: "Doctor Schedule",
    subtitle: "Today's session load by provider",
    url: "/patient-flow",
    keywords: ["doctor schedule", "provider schedule", "session load"],
    category: "Charts & Views",
  },
  {
    id: "chart-avg-wait-analytics",
    title: "Average Wait Time Chart",
    subtitle: "Current vs. AI-optimized by day of week",
    url: "/analytics",
    keywords: ["average wait chart", "wait comparison", "weekly wait"],
    category: "Charts & Views",
  },
  {
    id: "chart-throughput-hourly",
    title: "Patients Seen per Hour",
    subtitle: "Hourly throughput comparison chart",
    url: "/analytics",
    keywords: ["patients per hour chart", "hourly throughput", "seen per hour"],
    category: "Charts & Views",
  },
  {
    id: "chart-operational-profile",
    title: "Operational Profile",
    subtitle: "Multi-dimensional radar comparison",
    url: "/analytics",
    keywords: ["operational profile", "radar chart", "spider chart", "multi-dimensional"],
    aliases: ["radar"],
    category: "Charts & Views",
  },
  {
    id: "chart-outcome-summary",
    title: "Outcome Summary",
    subtitle: "7-day rolling AI optimization results",
    url: "/analytics",
    keywords: ["outcome summary", "7 day", "rolling comparison", "results summary"],
    category: "Charts & Views",
  },
  {
    id: "chart-simulation-forecast",
    title: "Simulation Forecast",
    subtitle: "Baseline vs. your scenario — next 60 minutes",
    url: "/simulation",
    keywords: ["simulation forecast", "baseline vs scenario", "what-if chart"],
    category: "Charts & Views",
  },
  {
    id: "chart-ai-alerts",
    title: "AI Alerts Panel",
    subtitle: "Live bottleneck and congestion warnings",
    url: "/",
    keywords: ["ai alerts", "alerts panel", "warnings", "bottleneck signals"],
    aliases: ["alert panel"],
    category: "Charts & Views",
  },

  // ── Recommendations ────────────────────────────────────────────────────────
  {
    id: "rec-room-4",
    title: "Reassign Room 4 to Urgent Care",
    subtitle: "Room allocation — High impact, 92% confidence",
    url: "/recommendations",
    keywords: ["room 4", "reassign", "urgent care", "room allocation"],
    category: "Recommendations",
  },
  {
    id: "rec-nurse-intake",
    title: "Shift Nurse to Intake Station",
    subtitle: "Staffing — High impact, reduces check-in time",
    url: "/recommendations",
    keywords: ["nurse", "intake", "check-in", "staffing", "front desk"],
    category: "Recommendations",
  },
  {
    id: "rec-delay-appointments",
    title: "Delay Low-Priority Appointments",
    subtitle: "Scheduling — Medium impact, flatten 14:30 peak",
    url: "/recommendations",
    keywords: ["delay", "appointments", "pediatrics", "low priority", "stagger"],
    category: "Recommendations",
  },
  {
    id: "rec-overflow-checkin",
    title: "Open Overflow Check-In Station",
    subtitle: "Capacity — High impact, activate secondary kiosk row",
    url: "/recommendations",
    keywords: ["overflow", "check-in", "kiosk", "intake", "east entrance"],
    category: "Recommendations",
  },
  {
    id: "rec-dr-chen",
    title: "Reallocate Dr. Chen's Schedule",
    subtitle: "Scheduling — Move Cardiology slots from 15:00 to 11:30",
    url: "/recommendations",
    keywords: ["dr chen", "chen schedule", "cardiology slots", "rebalance"],
    category: "Recommendations",
  },
  {
    id: "rec-radiology-prestage",
    title: "Pre-Stage Radiology Referrals",
    subtitle: "Coordination — Reserve imaging slots for Cardiology burst",
    url: "/recommendations",
    keywords: ["radiology", "referrals", "imaging", "coordination", "pre-stage"],
    category: "Recommendations",
  },
  {
    id: "rec-category-staffing",
    title: "Staffing Recommendations",
    subtitle: "Nurse and provider reallocation suggestions",
    url: "/recommendations",
    keywords: ["staffing recs", "staff recommendations", "nurse shift"],
    category: "Recommendations",
  },
  {
    id: "rec-category-capacity",
    title: "Capacity Recommendations",
    subtitle: "Overflow, rooms, and intake expansion suggestions",
    url: "/recommendations",
    keywords: ["capacity recs", "capacity recommendations", "overflow"],
    category: "Recommendations",
  },

  // ── Simulation Controls ────────────────────────────────────────────────────
  {
    id: "sim-arrivals",
    title: "Patient Arrivals",
    subtitle: "Simulation slider — patients per hour (5–45)",
    url: "/simulation",
    keywords: ["arrivals", "arrival rate", "patients per hour", "volume"],
    category: "Simulation",
  },
  {
    id: "sim-doctors",
    title: "Doctors on Shift",
    subtitle: "Simulation slider — provider count (2–14)",
    url: "/simulation",
    keywords: ["doctors shift", "doctor count", "providers on shift"],
    category: "Simulation",
  },
  {
    id: "sim-rooms",
    title: "Open Exam Rooms",
    subtitle: "Simulation slider — room count (4–18)",
    url: "/simulation",
    keywords: ["open rooms", "exam room count", "room capacity"],
    category: "Simulation",
  },
  {
    id: "sim-appt-duration",
    title: "Avg Appointment Duration",
    subtitle: "Simulation slider — minutes per visit (10–45)",
    url: "/simulation",
    keywords: ["appointment duration", "visit length", "appt length", "minutes per visit"],
    aliases: ["appointment length"],
    category: "Simulation",
  },
  {
    id: "sim-overflow",
    title: "Open Overflow Station",
    subtitle: "Toggle — adds +1 doctor and +2 rooms instantly",
    url: "/simulation",
    keywords: ["overflow station", "overflow toggle", "extra capacity", "surge mode"],
    category: "Simulation",
  },
  {
    id: "sim-reset",
    title: "Reset Simulation",
    subtitle: "Restore all controls to default baseline values",
    url: "/simulation",
    keywords: ["reset", "restore defaults", "clear simulation", "start over"],
    category: "Simulation",
  },
  {
    id: "sim-ai-commentary",
    title: "AI Commentary",
    subtitle: "Live narrative forecast based on your scenario",
    url: "/simulation",
    keywords: ["ai commentary", "narrative", "forecast explanation", "simulation summary"],
    category: "Simulation",
  },
  {
    id: "alert-pediatrics-surge",
    title: "Pediatrics Congestion Alert",
    subtitle: "High congestion predicted within 25 minutes — +32% arrival rate",
    url: "/",
    keywords: ["pediatrics alert", "pediatrics congestion", "surge alert", "overflow intake"],
    category: "Simulation",
  },
  {
    id: "alert-cardiology-wait",
    title: "Cardiology Wait Time Alert",
    subtitle: "Wait times spike 2–3 PM — bookings cluster at 14:30",
    url: "/",
    keywords: ["cardiology alert", "cardiology wait", "14:30", "afternoon wait"],
    category: "Simulation",
  },
  {
    id: "alert-room-capacity",
    title: "Room Capacity Alert",
    subtitle: "Utilization approaching critical — consider reassigning Room 4",
    url: "/",
    keywords: ["room capacity alert", "critical threshold", "room utilization alert"],
    category: "Simulation",
  },
];

export const SEARCH_CATEGORY_ORDER: SearchCategory[] = [
  "Pages",
  "Departments",
  "Flow Stages",
  "Staff & Rooms",
  "Metrics",
  "Charts & Views",
  "Recommendations",
  "Simulation",
];

export const POPULAR_SEARCHES = [
  "Wait Time",
  "Pediatrics",
  "Simulation",
  "Room 4",
  "Check-In",
  "AI Recommendations",
  "Congestion",
  "Dr. Chen",
];
