/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientFlowRouteImport } from './routes/patient-flow'
import { Route as IndexRouteImport } from './routes/index'

const PatientFlowRoute = PatientFlowRouteImport.update({
  id: '/patient-flow',
  path: '/patient-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patient-flow': typeof PatientFlowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient-flow': typeof PatientFlowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patient-flow': typeof PatientFlowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patient-flow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patient-flow'
  id: '__root__' | '/' | '/patient-flow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientFlowRoute: typeof PatientFlowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient-flow': {
      id: '/patient-flow'
      path: '/patient-flow'
      fullPath: '/patient-flow'
      preLoaderRoute: typeof PatientFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientFlowRoute: PatientFlowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
